// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";

var userAgent = "oikos-bot/0.1.0-beta";

var apiVersion = "2022-11-28";

async function apiRequest(token, method, endpoint, body) {
  var url = "https://api.github.com" + endpoint;
  var headers = {
    Authorization: "Bearer " + token,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": apiVersion,
    "User-Agent": userAgent,
    "Content-Type": "application/json"
  };
  try {
    var response = body !== undefined ? await globalThis.fetch(url, {
            method: method,
            headers: headers,
            body: JSON.stringify(body)
          }) : await globalThis.fetch(url, {
            method: method,
            headers: headers
          });
    if (response.ok) {
      var json = await response.json();
      return {
              TAG: "Ok",
              _0: json
            };
    }
    var status = response.status;
    var errorBody = await response.text();
    return {
            TAG: "Error",
            _0: "GitHub API error " + String(status) + ": " + errorBody
          };
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    var jsExn = Caml_js_exceptions.as_js_exn(exn);
    var msg = jsExn !== undefined ? Belt_Option.getWithDefault(Caml_option.valFromOption(jsExn).message, "Unknown error") : "Unknown error";
    return {
            TAG: "Error",
            _0: "API request failed: " + msg
          };
  }
}

async function postPRComment(token, owner, repo, prNumber, body) {
  var endpoint = "/repos/" + owner + "/" + repo + "/issues/" + String(prNumber) + "/comments";
  var payload = Js_dict.fromArray([[
          "body",
          body
        ]]);
  var result = await apiRequest(token, "POST", endpoint, payload);
  if (result.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: result._0
          };
  }
  var obj = Js_json.decodeObject(result._0);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Invalid JSON response"
          };
  }
  var id = Js_dict.get(obj, "id");
  if (id === undefined) {
    return {
            TAG: "Error",
            _0: "No comment ID in response"
          };
  }
  var num = Js_json.decodeNumber(id);
  if (num !== undefined) {
    return {
            TAG: "Ok",
            _0: num | 0
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid comment ID in response"
          };
  }
}

async function updateComment(token, owner, repo, commentId, body) {
  var endpoint = "/repos/" + owner + "/" + repo + "/issues/comments/" + String(commentId);
  var payload = Js_dict.fromArray([[
          "body",
          body
        ]]);
  var result = await apiRequest(token, "PATCH", endpoint, payload);
  if (result.TAG === "Ok") {
    return {
            TAG: "Ok",
            _0: undefined
          };
  } else {
    return {
            TAG: "Error",
            _0: result._0
          };
  }
}

async function createCheckRun(token, owner, repo, headSha, name, conclusion, title, summary) {
  var endpoint = "/repos/" + owner + "/" + repo + "/check-runs";
  var payload = Js_dict.fromArray([
        [
          "name",
          name
        ],
        [
          "head_sha",
          headSha
        ],
        [
          "status",
          "completed"
        ],
        [
          "conclusion",
          conclusion
        ],
        [
          "output",
          Js_dict.fromArray([
                [
                  "title",
                  title
                ],
                [
                  "summary",
                  summary
                ]
              ])
        ]
      ]);
  var result = await apiRequest(token, "POST", endpoint, payload);
  if (result.TAG !== "Ok") {
    return {
            TAG: "Error",
            _0: result._0
          };
  }
  var obj = Js_json.decodeObject(result._0);
  if (obj === undefined) {
    return {
            TAG: "Error",
            _0: "Invalid JSON response"
          };
  }
  var id = Js_dict.get(obj, "id");
  if (id === undefined) {
    return {
            TAG: "Error",
            _0: "No check run ID in response"
          };
  }
  var num = Js_json.decodeNumber(id);
  if (num !== undefined) {
    return {
            TAG: "Ok",
            _0: num | 0
          };
  } else {
    return {
            TAG: "Error",
            _0: "Invalid check run ID in response"
          };
  }
}

async function getPullRequest(token, owner, repo, prNumber) {
  var endpoint = "/repos/" + owner + "/" + repo + "/pulls/" + String(prNumber);
  return await apiRequest(token, "GET", endpoint, undefined);
}

async function getRepository(token, owner, repo) {
  var endpoint = "/repos/" + owner + "/" + repo;
  return await apiRequest(token, "GET", endpoint, undefined);
}

export {
  userAgent ,
  apiVersion ,
  apiRequest ,
  postPRComment ,
  updateComment ,
  createCheckRun ,
  getPullRequest ,
  getRepository ,
}
/* No side effect */
