// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Config from "./Config.res.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_string from "rescript/lib/es6/js_string.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function getGrade(score) {
  if (score >= 90.0) {
    return "A";
  } else if (score >= 80.0) {
    return "B";
  } else if (score >= 70.0) {
    return "C";
  } else if (score >= 60.0) {
    return "D";
  } else {
    return "F";
  }
}

function getGradeEmoji(grade) {
  switch (grade) {
    case "A" :
        return "🏆";
    case "B" :
        return "✨";
    case "C" :
        return "👍";
    case "D" :
        return "⚠️";
    default:
      return "🚨";
  }
}

function getStatusEmoji(score) {
  if (score >= 70.0) {
    return "✅";
  } else if (score >= 50.0) {
    return "⚠️";
  } else {
    return "❌";
  }
}

function severityToString(s) {
  switch (s) {
    case "Blocking" :
        return "blocking";
    case "High" :
        return "high";
    case "Medium" :
        return "medium";
    case "Low" :
        return "low";
    case "Info" :
        return "info";
    
  }
}

function generatePRComment(analysis, mode) {
  var grade = getGrade(analysis.health.total);
  var gradeEmoji = getGradeEmoji(grade);
  var healthLine = "### Overall Health: " + gradeEmoji + " " + grade + " (" + String(analysis.health.total) + "/100)\n\n";
  var scoreTable = "| Metric | Score | Status |\n|--------|-------|--------|\n" + ("| 🌍 Ecological | " + String(analysis.eco.score) + " | " + getStatusEmoji(analysis.eco.score) + " |\n") + ("| 📊 Economic | " + String(analysis.econ.score) + " | " + getStatusEmoji(analysis.econ.score) + " |\n") + ("| ⚙️ Quality | " + String(analysis.quality.score) + " | " + getStatusEmoji(analysis.quality.score) + " |\n\n");
  var violationsSection;
  if (analysis.violations.length !== 0) {
    var violationLines = Belt_Array.joinWith(Belt_Array.map(analysis.violations, (function (v) {
                var icon = v.severity === "Blocking" ? "🚫" : "⚠️";
                return icon + " **" + v.policy + "**: " + v.message + "\n";
              })), "", (function (s) {
            return s;
          }));
    violationsSection = "### ⚠️ Policy Violations\n\n" + violationLines + "\n";
  } else {
    violationsSection = "";
  }
  var recommendationsSection;
  if (analysis.recommendations.length !== 0 && mode !== "Regulator") {
    var maxRecs = mode === "Consultant" ? 10 : 5;
    var topRecs = Belt_Array.slice(analysis.recommendations, 0, maxRecs);
    var recLines = Belt_Array.joinWith(Belt_Array.map(topRecs, (function (r) {
                var confidence = r.confidence * 100.0 | 0;
                return "- **" + r.action + "** (" + String(confidence) + "% confidence): " + r.reason + "\n";
              })), "", (function (s) {
            return s;
          }));
    recommendationsSection = "### 💡 Recommendations\n\n" + recLines + "\n";
  } else {
    recommendationsSection = "";
  }
  var ps = analysis.econ.paretoStatus;
  var paretoSection;
  if (ps !== undefined) {
    var status;
    if (ps.isOptimal) {
      status = "✅ This code is on the Pareto frontier - no dominated trade-offs detected.\n\n";
    } else {
      var imps = ps.improvements;
      var improvements = imps !== undefined ? Belt_Array.joinWith(Belt_Array.map(imps, (function (i) {
                    return "- " + i + "\n";
                  })), "", (function (s) {
                return s;
              })) : "";
      status = "📍 Distance from Pareto frontier: " + String(ps.distance) + "\n\n" + (
        improvements !== "" ? "Potential Pareto improvements:\n" + improvements + "\n" : ""
      );
    }
    paretoSection = "### 📈 Pareto Analysis\n\n" + status;
  } else {
    paretoSection = "";
  }
  var footer = "---\n*Analyzed by [Oikos Bot](https://github.com/hyperpolymath/oikos-bot) | " + ("Mode: " + Config.modeToString(mode) + " | ") + "[Learn more about eco-friendly coding](https://greensoftware.foundation/)*\n";
  return "## 🏛️ Oikos Analysis\n\n" + healthLine + scoreTable + violationsSection + recommendationsSection + paretoSection + footer;
}

function generateSARIF(analysis) {
  var rules = [
    Js_dict.fromArray([
          [
            "id",
            "eco/eco-minimum"
          ],
          [
            "name",
            "EcoMinimum"
          ],
          [
            "shortDescription",
            Js_dict.fromArray([[
                    "text",
                    "Eco minimum threshold not met"
                  ]])
          ]
        ]),
    Js_dict.fromArray([
          [
            "id",
            "eco/eco-standard"
          ],
          [
            "name",
            "EcoStandard"
          ],
          [
            "shortDescription",
            Js_dict.fromArray([[
                    "text",
                    "Eco standard threshold not met"
                  ]])
          ]
        ])
  ];
  var results = Belt_Array.map(analysis.violations, (function (v) {
          return Js_dict.fromArray([
                      [
                        "ruleId",
                        "eco/" + Js_string.replace("_", "-", v.policy)
                      ],
                      [
                        "level",
                        v.severity === "Blocking" ? "error" : "warning"
                      ],
                      [
                        "message",
                        Js_dict.fromArray([[
                                "text",
                                v.message
                              ]])
                      ]
                    ]);
        }));
  return Js_dict.fromArray([
              [
                "$schema",
                "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json"
              ],
              [
                "version",
                "2.1.0"
              ],
              [
                "runs",
                [Js_dict.fromArray([
                        [
                          "tool",
                          Js_dict.fromArray([[
                                  "driver",
                                  Js_dict.fromArray([
                                        [
                                          "name",
                                          "oikos-bot"
                                        ],
                                        [
                                          "version",
                                          "0.1.0-beta"
                                        ],
                                        [
                                          "informationUri",
                                          "https://github.com/hyperpolymath/oikos-bot"
                                        ],
                                        [
                                          "rules",
                                          Belt_Array.map(rules, (function (prim) {
                                                  return prim;
                                                }))
                                        ]
                                      ])
                                ]])
                        ],
                        [
                          "results",
                          Belt_Array.map(results, (function (prim) {
                                  return prim;
                                }))
                        ]
                      ])]
              ]
            ]);
}

export {
  getGrade ,
  getGradeEmoji ,
  getStatusEmoji ,
  severityToString ,
  generatePRComment ,
  generateSARIF ,
}
/* No side effect */
